[package]
name = "contenttypechangeservice"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.4.0"
reqwest =  { version = "0.12.24", features = ["stream"] }
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
